-- Tables referenced by the frontend but never captured as migrations.
-- Schemas reconstructed from src/integrations/supabase/types.ts. These come
-- back empty (old project deleted, no backup) and need repopulating from their
-- respective data sources (MBTA API, visitor tracking, etc.).

-- ---------- Insights (RAG insight cards) ----------
CREATE TABLE IF NOT EXISTS public.insights (
  uuid UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  insight_text TEXT NOT NULL,
  category TEXT,
  subcategory TEXT,
  description TEXT,
  amount NUMERIC,
  percentage_of_budget NUMERIC,
  per_capita NUMERIC,
  priority_level TEXT,
  source_page TEXT,
  trend TEXT,
  trend_percentage TEXT,
  year NUMERIC
);

-- ---------- Visitor tracking ----------
CREATE TABLE IF NOT EXISTS public.visitor_tracking (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  visitor_id TEXT NOT NULL,
  session_id TEXT NOT NULL,
  page_path TEXT NOT NULL,
  ip_address TEXT,
  user_agent TEXT,
  browser TEXT,
  device_type TEXT,
  screen_size TEXT,
  referrer TEXT,
  country TEXT,
  region TEXT,
  city TEXT,
  is_returning BOOLEAN,
  visit_duration NUMERIC,
  visit_timestamp TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_visitor_tracking_visit_ts ON public.visitor_tracking(visit_timestamp);
CREATE INDEX IF NOT EXISTS idx_visitor_tracking_session ON public.visitor_tracking(session_id);

-- ---------- MBTA ----------
CREATE TABLE IF NOT EXISTS public.mbta_travel_times (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  route_id TEXT NOT NULL,
  direction INTEGER NOT NULL,
  from_stop TEXT NOT NULL,
  to_stop TEXT NOT NULL,
  date TEXT NOT NULL,
  dep_dt TEXT NOT NULL,
  arr_dt TEXT NOT NULL,
  dep_dt_key TEXT,
  time_key TEXT,
  travel_time_sec NUMERIC NOT NULL,
  benchmark_travel_time_sec NUMERIC NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_mbta_travel_times_route ON public.mbta_travel_times(route_id, date);

CREATE TABLE IF NOT EXISTS public.mbta_alerts (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  header TEXT NOT NULL,
  description TEXT,
  type TEXT NOT NULL,
  current BOOLEAN NOT NULL DEFAULT false,
  upcoming BOOLEAN NOT NULL DEFAULT false,
  start_time TIMESTAMPTZ,
  end_time TIMESTAMPTZ,
  stops TEXT[],
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.mbta_transit_lines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  line_id TEXT NOT NULL,
  type TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.mbta_stations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  station_id TEXT NOT NULL,
  line_id TEXT NOT NULL,
  stop_name TEXT NOT NULL,
  short_name TEXT,
  order_num NUMERIC NOT NULL,
  accessible BOOLEAN,
  enclosed_bike_parking BOOLEAN,
  pedal_park BOOLEAN,
  terminus BOOLEAN,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.mbta_station_stops (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  station_id TEXT NOT NULL,
  stop_id TEXT NOT NULL,
  direction_id TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.mbta_bus_connections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  station_id TEXT NOT NULL,
  bus_route TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.mbta_line_directions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  line_id TEXT NOT NULL,
  direction_id TEXT NOT NULL,
  direction_name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ---------- Budget summaries (best-effort; not in types.ts) ----------
CREATE TABLE IF NOT EXISTS public.budget_summaries (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  fiscal_year INTEGER,
  total_budget NUMERIC,
  summary TEXT,
  data JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ---------- Visitor count RPC ----------
CREATE OR REPLACE FUNCTION public.get_visitor_count_by_day(days_back INTEGER DEFAULT 30)
RETURNS TABLE (visit_date DATE, visitor_count BIGINT)
LANGUAGE sql
STABLE
AS $$
  SELECT visit_timestamp::date AS visit_date,
         COUNT(DISTINCT visitor_id) AS visitor_count
  FROM public.visitor_tracking
  WHERE visit_timestamp >= NOW() - (days_back || ' days')::interval
  GROUP BY visit_timestamp::date
  ORDER BY visit_date;
$$;

-- ---------- Public access (matches the project's permissive pattern) ----------
DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'insights','visitor_tracking','mbta_travel_times','mbta_alerts',
    'mbta_transit_lines','mbta_stations','mbta_station_stops',
    'mbta_bus_connections','mbta_line_directions','budget_summaries'
  ] LOOP
    EXECUTE format('ALTER TABLE public.%1$s ENABLE ROW LEVEL SECURITY;', t);
    EXECUTE format('CREATE POLICY "public select %1$s" ON public.%1$s FOR SELECT TO public USING (true);', t);
    EXECUTE format('CREATE POLICY "public insert %1$s" ON public.%1$s FOR INSERT TO public WITH CHECK (true);', t);
    EXECUTE format('CREATE POLICY "public update %1$s" ON public.%1$s FOR UPDATE TO public USING (true) WITH CHECK (true);', t);
  END LOOP;
END $$;
