// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dslaxzbzsdzxjcsdbruf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzbGF4emJ6c2R6eGpjc2RicnVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjg3NjkyNjYsImV4cCI6MjA0NDM0NTI2Nn0.w-8KBZLOJy9OPJRp8IYl4AbQKpdyOst3V-tElrYMKqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);